### ISSUE TITLE
IP Address Sorting Result Bug

### ISSUE THREAD

**Issue by izzatbey** [fadhilyori/subping#12]
**Describe the bug**
I got an issue on your subping IP Address Result that not sorted in a correct way as shown below :

![image](https://github.com/fadhilyori/subping/assets/61180188/fdc8d49f-3578-45d3-9798-24b128d59aa6)

**Expected behavior**
It Should be appeard in a sequence of IP Address based on the IP Ranges.

please notice this if you find the same issue as mine

**Comment by fadhilyori** [comment]
Thank you for bringing up this issue in my GitHub project. 

I sincerely appreciate your effort in identifying and highlighting it. I kindly request your assistance in resolving this matter, and I would greatly appreciate it if you could lend a hand in fixing this. 😁

**Comment by izzatbey** [comment]
Alright, I already came up with the solution for this bug :

![image](https://github.com/fadhilyori/subping/assets/61180188/bdc7bb38-6092-4ce5-a17c-651895680d40)


**Description**
So the problem with this bug is that the original sorting you implement on the code is based on String which means by lexicographic order as a string of an IP Address was read from left to right.

**Solution**
on the code, I change the extracted slice into a bytes of IP Address, so it came up with the sorting of the slice with an Insertion Sorting Algorithm, then after that, I change the byte into a String on the for-each loop

**Comment by izzatbey** [comment]
I'll create the Pull Request of the solution
