### ISSUE TITLE
Some targets are missing from the results after running the `Run()` command sometimes.

### ISSUE THREAD

**Issue by fadhilyori** [fadhilyori/subping#14]
**Describe the bug:**
Some targets are missing from the results after running the `Run()` command sometimes.

**To Reproduce:**
1. Modify `main.go` to print the length of `s.Results` and `s.Targets`.
2. Run the command using large hosts, for example, `/16` or `/24`, and use high concurrency (256).
3. The length of `s.Results` sometimes does not match the length of `s.Targets`. If we print the map, we can observe that some IP addresses are not present.

**Expected behavior:**
The length of `s.Results` should be the same as the length of `s.Targets`.

**Screenshots:**
The IP address `127.0.0.3` is not present in `s.Results`.
![image](https://github.com/fadhilyori/subping/assets/21302824/723421cc-064f-40f9-9c37-2b06a636074d)

**Additional context**
This issue arises due to unsynchronized data stores among goroutines.

**Comment by izzatbey** [comment]
i've got same issue here as you said above as shown below :
![image](https://github.com/fadhilyori/subping/assets/61180188/8b609bfa-e993-453c-a90c-491ee073461f)

and i've come out with the solution about this, i'll create the pull request of the solution for you
![image](https://github.com/fadhilyori/subping/assets/61180188/ef96ca7c-ee6d-4a6b-887b-08117b13ebe7)
