### ISSUE TITLE
Dockerize App

### ISSUE THREAD

**Issue by alfiyansys** [fadhilyori/subping#22]
**Is your feature request related to a problem? Please describe.**
It's sometimes just can't build on legacy systems, e.g. Ubuntu 16.04, because of lack of newest golang support

**Describe the solution you'd like**
Dockerize the app, its can be run as simply : 
`docker run subping <args>`

**Describe alternatives you've considered**
No alternatives

**Comment by fadhilyori** [comment]
Thank you, this will be useful also for automation. Added to [milestone v1.1.0](https://github.com/fadhilyori/subping/milestone/2)
