### ISSUE TITLE
SIGSEGV: Pinging...panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alfiyansys** [fadhilyori/subping#6]
![image](https://github.com/fadhilyori/subping/assets/1548140/b27c952d-2e69-4cb7-877a-7325820b442f)

**Comment by fadhilyori** [comment]
Hi @alfiyansys,

Thanks for reporting the error! I'm aware of the issue and working on a fix. I'll keep you updated on the progress and let you know once it's resolved.

Feel free to reach out if you have any questions or need assistance.

**Comment by fadhilyori** [comment]
Hi @alfiyansys ,

I've already made a pull request (PR) to address the problem. You can find the PR https://github.com/fadhilyori/subping/pull/8 for review.

Please take a moment to check if the proposed changes resolve the issue. Feel free to test it out and provide feedback. I appreciate your help in verifying the fix.

**Comment by alfiyansys** [comment]
let me check

**Comment by alfiyansys** [comment]
![image](https://github.com/fadhilyori/subping/assets/1548140/8acf76ff-d5ae-45a9-9590-e39d677f6187)

confirmed to be working

**Comment by fadhilyori** [comment]
PR #8 has already been merged, thank you
